# Generated by Django 4.2.13 on 2024-07-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_appointment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='approved',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
